using System;
using System.Data;
using System.Data.Common;
using Oracle.ManagedDataAccess.Client;

namespace EntitySpaces.MetadataEngine.Oracle
{
	public class OracleColumns : Columns
	{
		public OracleColumns()
		{

		}

        internal  DataColumn f_TypeName;
        internal DataColumn f_TypeNameComplete;

        override internal void LoadForTable()
        {
            try
            {
                string query =
                    "SELECT " +
                    "  atc.COLUMN_NAME, " +
                    // REGEXP_SUBSTR strips precision from type name (e.g. 'TIMESTAMP(6)' → 'TIMESTAMP')
                    // so it matches entries in esLanguages.xml which use base type names only.
                    // TYPE_NAMECOMPLETE keeps the full type including precision for DDL generation.
                    "  REGEXP_SUBSTR(atc.DATA_TYPE, '^[A-Za-z0-9 ]+') AS TYPE_NAME, " +
                    "  atc.DATA_TYPE AS TYPE_NAMECOMPLETE, " +
                    "  atc.DATA_LENGTH AS CHARACTER_MAXIMUM_LENGTH, " +
                    "  atc.DATA_PRECISION AS NUMERIC_PRECISION, " +
                    "  atc.DATA_SCALE AS NUMERIC_SCALE, " +
                    // VIRTUAL_COLUMN from ALL_TAB_COLS — not always available in ALL_TAB_COLUMNS.
                    // LEFT JOIN on OWNER + TABLE_NAME + COLUMN_NAME works in Cloud ATP and
                    // on-premise multi-schema deployments (unlike USER_TAB_COLS which only
                    // sees the connected user's objects).
                    "  CASE utc.VIRTUAL_COLUMN WHEN 'YES' THEN 'YES' ELSE 'NO' END AS IS_COMPUTED, " +
                    // Convert NULLABLE 'Y'/'N' to '1'/'0' — consistent with LoadForView
                    // and with what the base Column engine expects for IsNullable
                    "  CASE WHEN atc.NULLABLE = 'Y' THEN '1' ELSE '0' END AS IS_NULLABLE, " +
                    "  atc.DATA_DEFAULT AS COLUMN_DEFAULT, " +
                    "  atc.COLUMN_ID AS ORDINAL_POSITION " +
                    "FROM ALL_TAB_COLUMNS atc " +
                    "LEFT JOIN ALL_TAB_COLS utc " +
                    "  ON utc.OWNER       = atc.OWNER " +
                    " AND utc.TABLE_NAME  = atc.TABLE_NAME " +
                    " AND utc.COLUMN_NAME = atc.COLUMN_NAME " +
                    "WHERE atc.OWNER = '" + this.Table.Database.SchemaOwner + "' " +
                    "  AND atc.TABLE_NAME = '" + this.Table.FullName + "' " +
                    "ORDER BY atc.COLUMN_ID";

                // Single connection reused for both queries
                using (IDbConnection cn = ConnectionHelper.CreateConnection(this.dbRoot, this.Table.Database.Name))
                {
                    // --- Query 1: column metadata ---
                    DataTable metaData = new DataTable();
                    new OracleDataAdapter(query, (OracleConnection)cn).Fill(metaData);

                    if (metaData.Columns.Contains("TYPE_NAME"))
                        f_TypeName = metaData.Columns["TYPE_NAME"];

                    if (metaData.Columns.Contains("TYPE_NAMECOMPLETE"))
                        f_TypeNameComplete = metaData.Columns["TYPE_NAMECOMPLETE"];

                    PopulateArray(metaData);

                    // --- Query 2: detect GENERATED BY DEFAULT AS IDENTITY columns ---
                    // Oracle 12c+ identity columns use internal sequences (ISEQ$$_XXXXX)
                    // detected via IDENTITY_COLUMN flag — not by joining ALL_SEQUENCES
                    // which only works with manually named sequences
                    string identityQuery =
                        "SELECT COLUMN_NAME " +
                        "FROM ALL_TAB_COLUMNS " +
                        "WHERE OWNER = '" + this.Table.Database.SchemaOwner + "' " +
                        "  AND TABLE_NAME = '" + this.Table.Name + "' " +
                        "  AND IDENTITY_COLUMN = 'YES'";

                    DataTable seqData = new DataTable();
                    new OracleDataAdapter(identityQuery, (OracleConnection)cn).Fill(seqData);

                    foreach (DataRow row in seqData.Rows)
                    {
                        string colName = row["COLUMN_NAME"] as string;
                        OracleColumn col = this[colName] as OracleColumn;
                        if (col != null)
                        {
                            col._isAutoKey = true;
                            col._autoInc = 1;  // IDENTITY default START WITH
                            col._autoSeed = 1;  // IDENTITY default INCREMENT BY
                        }
                    }
                }
            }
            catch
            {
                throw;
            }
        }


        override internal void LoadForView()
        {
            try
            {
                // Determine schema owner and object name dynamically —
                // this method is shared between Table and View contexts
                string schemaOwner = (this.Table != null)
                    ? this.Table.Database.SchemaOwner
                    : this.View.Database.SchemaOwner;

                string objectName = (this.Table != null)
                    ? this.Table.Name
                    : this.View.Name;

                string dbName = (this.Table != null)
                    ? this.Table.Database.Name
                    : this.View.Database.Name;

                string query =
                    "SELECT " +
                    "  atc.COLUMN_NAME, " +
                    // REGEXP_SUBSTR strips precision from type name (e.g. 'TIMESTAMP(6)' → 'TIMESTAMP')
                    // so it matches entries in esLanguages.xml which use base type names only.
                    // TYPE_NAMECOMPLETE keeps the full type including precision for DDL generation.
                    "  REGEXP_SUBSTR(data_type, '^[A-Za-z0-9 ]+') AS TYPE_NAME, " +
                    "  atc.DATA_TYPE AS TYPE_NAMECOMPLETE, " +
                    "  atc.DATA_LENGTH AS CHARACTER_MAXIMUM_LENGTH, " +
                    "  atc.DATA_PRECISION AS NUMERIC_PRECISION, " +
                    "  atc.DATA_SCALE AS NUMERIC_SCALE, " +
                    // VIRTUAL_COLUMN from ALL_TAB_COLS — not always available in ALL_TAB_COLUMNS.
                    // LEFT JOIN on OWNER + TABLE_NAME + COLUMN_NAME works in Cloud ATP and
                    // on-premise multi-schema deployments (unlike USER_TAB_COLS which only
                    // sees the connected user's objects).
                    "  CASE utc.VIRTUAL_COLUMN WHEN 'YES' THEN 'YES' ELSE 'NO' END AS IS_COMPUTED, " +
                    // Convert NULLABLE 'Y'/'N' to '1'/'0' — consistent with LoadForTable
                    // and with what the base Column engine expects for IsNullable
                    "  CASE WHEN atc.NULLABLE = 'Y' THEN '1' ELSE '0' END AS IS_NULLABLE, " +
                    "  atc.DATA_DEFAULT AS COLUMN_DEFAULT, " +
                    "  atc.COLUMN_ID AS ORDINAL_POSITION " +
                    "FROM all_tab_columns atc " +
                    "LEFT JOIN ALL_TAB_COLS utc " +
                    "  ON utc.OWNER       = atc.OWNER " +
                    " AND utc.TABLE_NAME  = atc.TABLE_NAME " +
                    " AND utc.COLUMN_NAME = atc.COLUMN_NAME " +
                    "WHERE atc.OWNER = '" + schemaOwner + "' " +
                    "  AND atc.TABLE_NAME = '" + objectName + "' " +
                    "ORDER BY atc.COLUMN_ID";

                using (IDbConnection cn = ConnectionHelper.CreateConnection(this.dbRoot, dbName))
                {
                    DataTable metaData = new DataTable();

                    using (OracleDataAdapter adapter = new OracleDataAdapter(query, (OracleConnection)cn))
                    {
                        adapter.Fill(metaData);
                    }

                    if (metaData.Columns.Contains("TYPE_NAME"))
                        f_TypeName = metaData.Columns["TYPE_NAME"];

                    if (metaData.Columns.Contains("TYPE_NAMECOMPLETE"))
                        f_TypeNameComplete = metaData.Columns["TYPE_NAMECOMPLETE"];

                    PopulateArray(metaData);
                }
            }
            catch (Exception ex)
            {
                // LoadForView failed — let the exception propagate so the Studio
                // can surface the error instead of silently returning empty columns
                throw;
            }
        }

    } // end class
} // end namespace
