<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>esGacInstall</RootNamespace>
    <AssemblyName>esGacInstall</AssemblyName>
    
    <!-- Firmado de ensamblado -->
    <!--<SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\StrongNameKey\EntitySpaces.snk</AssemblyOriginatorKeyFile>-->
    
    <!-- Desactivar generación automática de info de ensamblado -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <!-- Archivos compartidos -->
    <Compile Include="..\SharedFiles\SharedVersion.cs" Link="SharedVersion.cs" />
  </ItemGroup>

  <ItemGroup>
    <!-- Clave de seguridad -->
    <!--<None Include="..\StrongNameKey\EntitySpaces.snk" Link="EntitySpaces.snk" />-->
    <None Include="app.config" />
  </ItemGroup>

</Project>
