<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
	<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
	<TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
	<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <RootNamespace>EntitySpaces.MetadataEngine.SQLite</RootNamespace>
    <AssemblyName>EntitySpaces.MetadataEngine.SQLite</AssemblyName>
    
    <!-- Firmado de ensamblado -->
    <!--<SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\StrongNameKey\EntitySpaces.snk</AssemblyOriginatorKeyFile>-->
    
    <!-- Desactivado para evitar conflictos con Properties\AssemblyInfo.cs y SharedVersion.cs -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EntitySpaces.MetadataEngine\EntitySpaces.MetadataEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!--<None Include="..\StrongNameKey\EntitySpaces.snk" Link="EntitySpaces.snk" />-->
  </ItemGroup>

  <ItemGroup>
    <!-- Referencia a paquete NuGet -->
    <PackageReference Include="System.Data.SQLite.Core" />
  </ItemGroup>

</Project>