<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Library</OutputType>
	<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
	<TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
	<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>EntitySpaces.AddIn.TemplateUI</RootNamespace>
    <AssemblyName>EntitySpaces.AddIn.TemplateUI</AssemblyName>
    
    <!-- Firmado de ensamblado -->
    <!--<SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\StrongNameKey\EntitySpaces.snk</AssemblyOriginatorKeyFile>-->
    
    <!-- Evitar conflictos con Properties\AssemblyInfo.cs y SharedVersion.cs -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EntitySpaces.MetadataEngine\EntitySpaces.MetadataEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Archivos vinculados desde carpetas superiores -->
    <Compile Include="..\..\SharedFiles\SharedVersion.cs" Link="SharedVersion.cs" />
    <!--<None Include="..\..\StrongNameKey\EntitySpaces.snk" Link="EntitySpaces.snk" />-->
  </ItemGroup>

</Project>