using System;
using System.Collections.Generic;
using System.Data;
using Oracle.ManagedDataAccess.Client;

using EntitySpaces.DynamicQuery;
using EntitySpaces.Interfaces;

namespace EntitySpaces.OracleManagedClientProvider
{
    class Shared
    {
        static public OracleCommand BuildDynamicInsertCommand(esDataRequest request, esEntitySavePacket packet)
        {
            Dictionary<string, OracleParameter> types = Cache.GetParameters(request);

            OracleCommand cmd = new OracleCommand();
            cmd.BindByName = true;
            if (request.CommandTimeout != null) cmd.CommandTimeout = request.CommandTimeout.Value;

            string comma = String.Empty;
            string into = String.Empty;
            string values = String.Empty;
            string computedColumns = String.Empty;
            string computedParameters = String.Empty;
            string computedComma = String.Empty;

            List<string> modifiedColumns = packet.ModifiedColumns;

            string sql = "BEGIN ";

            OracleParameter p = null;

            foreach (esColumnMetadata col in request.Columns)
            {
                if (col.IsAutoIncrement)
                {
                    p = CloneParameter(types[col.Name]);
                    p.Direction = ParameterDirection.Output;
                    p.Value = DBNull.Value;
                    cmd.Parameters.Add(p);

					// Oracle GENERATED BY DEFAULT AS IDENTITY — the value is assigned by Oracle
					// automatically in the INSERT. We retrieve it via RETURNING ... INTO
					// at the end of the INSERT. It is not included in INTO/VALUES.
					// The Output parameter is populated via the RETURNING clause added below.
                }
                else if (col.IsEntitySpacesConcurrency)
                {
                    p = CloneParameter(types[col.Name]);
                    p.Direction = ParameterDirection.Output;
                    cmd.Parameters.Add(p);

                    sql += p.ParameterName + " := 1; ";

                    into += comma;
                    into += Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose;
                    values += comma;
                    values += p.ParameterName;
                    comma = ", ";
                }
                else if (col.HasDefault && !IsColumnModified(packet, col))
                {
                    p = CloneParameter(types[col.Name]);
                    p.Direction = ParameterDirection.Output;
                    // ODP.NET requires DBNull.Value on Output parameters — null throws "Parameter cannot be null"
                    p.Value = DBNull.Value;
                    cmd.Parameters.Add(p);

                    computedColumns += computedComma + Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose;
                    computedParameters += computedComma + p.ParameterName;
                    computedComma = ", ";

                    if (col.CharacterMaxLength > 0)
                    {
                        p.Size = (int)col.CharacterMaxLength;
                    }
                }
            }

            esColumnMetadataCollection cols = request.Columns;

            #region Special Column Logic
            // Server-side special columns are filled by the DB (DEFAULT SYSTIMESTAMP
            // or trigger). Two things must change from the previous behavior:
            //
            //   1. Do NOT concatenate the ServerSideText value into the PL/SQL block.
            //      The value is the bareword "DateAdded", which Oracle rejects with
            //      PLS-00201 "identifier must be declared".
            //
            //   2. Do NOT include the column in the INSERT column list. The DB
            //      DEFAULT populates it; including it with a NULL placeholder produces
            //      ORA-01400 on the NOT NULL column.
            //
            // The value is retrieved via the RETURNING clause added below, and the
            // parameter is marked Output so the framework writes it back to
            // CurrentValues.
            if (cols.DateAdded != null && cols.DateAdded.IsServerSide)
            {
                p = CloneParameter(types[cols.DateAdded.ColumnName]);
                p.Direction = ParameterDirection.Output;
                cmd.Parameters.Add(p);
            }

            if (cols.DateModified != null && cols.DateModified.IsServerSide)
            {
                p = CloneParameter(types[cols.DateModified.ColumnName]);
                p.Direction = ParameterDirection.Output;
                cmd.Parameters.Add(p);
            }

            if (cols.AddedBy != null && cols.AddedBy.IsServerSide)
            {
                p = CloneParameter(types[cols.AddedBy.ColumnName]);
                p.Size = (int)cols.FindByColumnName(cols.AddedBy.ColumnName).CharacterMaxLength;
                p.Direction = ParameterDirection.Output;
                cmd.Parameters.Add(p);
            }

            if (cols.ModifiedBy != null && cols.ModifiedBy.IsServerSide)
            {
                p = CloneParameter(types[cols.ModifiedBy.ColumnName]);
                p.Size = (int)cols.FindByColumnName(cols.ModifiedBy.ColumnName).CharacterMaxLength;
                p.Direction = ParameterDirection.Output;
                cmd.Parameters.Add(p);
            }
            #endregion

            sql += "INSERT INTO " + CreateFullName(request) + " ";

            // Iterate request.Columns (canonical metadata) rather than the raw
            // ModifiedColumns list, so that property-name-keyed modifications
            // coming from ApplyPostSaveKeys resolve to the correct metadata.
            foreach (esColumnMetadata col in request.Columns)
            {
                if (col.IsAutoIncrement) continue;
                if (col.IsEntitySpacesConcurrency) continue;
                if (col.HasDefault && !IsColumnModified(packet, col)) continue;
                if (!IsColumnModified(packet, col)) continue;

                p = cmd.Parameters.Add(CloneParameter(types[col.Name]));

                object value = GetColumnValue(packet, col);
                p.Value = value != null ? value : DBNull.Value;

                into += comma;
                into += Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose;
                values += comma;
                values += p.ParameterName;
                comma = ", ";
            }

            // Collect RETURNING clause for GENERATED AS IDENTITY columns
            string returningCols = string.Empty;
            string returningParams = string.Empty;
            string returningComma = string.Empty;
            foreach (esColumnMetadata col in request.Columns)
            {
                if (col.IsAutoIncrement)
                {
                    OracleParameter rp = cmd.Parameters[types[col.Name].ParameterName];
                    returningCols   += returningComma + Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose;
                    returningParams += returningComma + rp.ParameterName;
                    returningComma = ", ";
                }
            }

            // Special columns also need to be pulled back through RETURNING so
            // the DB-assigned values reach the entity's CurrentValues.
            if (cols.DateAdded != null && cols.DateAdded.IsServerSide)
            {
                OracleParameter rp = cmd.Parameters[types[cols.DateAdded.ColumnName].ParameterName];
                returningCols += returningComma + Delimiters.ColumnOpen + cols.DateAdded.ColumnName + Delimiters.ColumnClose;
                returningParams += returningComma + rp.ParameterName;
                returningComma = ", ";
            }
            if (cols.DateModified != null && cols.DateModified.IsServerSide)
            {
                OracleParameter rp = cmd.Parameters[types[cols.DateModified.ColumnName].ParameterName];
                returningCols += returningComma + Delimiters.ColumnOpen + cols.DateModified.ColumnName + Delimiters.ColumnClose;
                returningParams += returningComma + rp.ParameterName;
                returningComma = ", ";
            }
            if (cols.AddedBy != null && cols.AddedBy.IsServerSide)
            {
                OracleParameter rp = cmd.Parameters[types[cols.AddedBy.ColumnName].ParameterName];
                returningCols += returningComma + Delimiters.ColumnOpen + cols.AddedBy.ColumnName + Delimiters.ColumnClose;
                returningParams += returningComma + rp.ParameterName;
                returningComma = ", ";
            }
            if (cols.ModifiedBy != null && cols.ModifiedBy.IsServerSide)
            {
                OracleParameter rp = cmd.Parameters[types[cols.ModifiedBy.ColumnName].ParameterName];
                returningCols += returningComma + Delimiters.ColumnOpen + cols.ModifiedBy.ColumnName + Delimiters.ColumnClose;
                returningParams += returningComma + rp.ParameterName;
                returningComma = ", ";
            }

            if (into.Length != 0)
            {
                sql += "(" + into + ") VALUES (" + values + ")";
                if (returningCols.Length > 0)
                    sql += " RETURNING " + returningCols + " INTO " + returningParams;
                sql += "; ";
            }
            else if (returningCols.Length > 0)
            {
                // INSERT con solo columnas auto-increment — Oracle las genera todas
                sql += "DEFAULT VALUES";
                sql += " RETURNING " + returningCols + " INTO " + returningParams;
                sql += "; ";
            }

            if (computedColumns.Length > 0)
            {
                string where = String.Empty;

                foreach (esColumnMetadata col in request.Columns)
                {
                    if (col.IsInPrimaryKey)
                    {
                        // We need the were clause if there are defaults to bring back
                        p = types[col.Name];

                        if (where.Length > 0) where += " AND ";
                        where += Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose + " = " + p.ParameterName;

                        if (!cmd.Parameters.Contains(p.ParameterName))
                        {
                            p = CloneParameter(p);
                            p.Direction = ParameterDirection.Output;
                            cmd.Parameters.Add(p);
                        }
                    }
                }

                sql += " SELECT " + computedColumns + " INTO " + computedParameters + " FROM " + CreateFullName(request) + " WHERE (" + where + ");";
            }

            sql += " END;";

            cmd.CommandText = sql;
            cmd.CommandType = CommandType.Text;
            return cmd;
        }

        static private void CreateInsertSQLSnippet(string colName, OracleParameter p, ref string into, ref string values, ref string comma)
        {
            into += comma;
            into += Delimiters.ColumnOpen + colName + Delimiters.ColumnClose;
            values += comma;
            values += p.ParameterName;
            comma = ", ";
        }

        //CREATE PROCEDURE "MYGENERATION"."proc_SeqTestUpdate" ( 
        //    pID IN "SeqTest"."ID"%type, 
        //    pTimeStamp IN OUT "SeqTest"."TimeStamp"%type, 
        //    pData IN "SeqTest"."Data"%type 
        //) 
        //IS 
        //    pConncurrency "SeqTest"."TimeStamp"%type := pTimeStamp;      

        //BEGIN 
        //    UPDATE "SeqTest" 
        //    SET 
        //        "TimeStamp" = "TimeStamp" + 1, 
        //        "Data"  = pData 
        //    WHERE 
        //        "ID" = pID 
        //    AND "TimeStamp" = pConncurrency 
        //; 

        //    IF SQL%ROWCOUNT = 1 THEN 
        //     pTimeStamp := (pConncurrency + 1); 
        //    ELSE 
        //     Raise_application_error(01403, 'NO RECORDS WERE UPDATED'); 
        //    END IF;  

        //END ;

        static public OracleCommand BuildDynamicUpdateCommand(esDataRequest request, esEntitySavePacket packet)
        {
            Dictionary<string, OracleParameter> types = Cache.GetParameters(request);

            OracleCommand cmd = new OracleCommand();
            cmd.BindByName = true;
            if (request.CommandTimeout != null) cmd.CommandTimeout = request.CommandTimeout.Value;

            string sql = string.Empty;

            bool hasConcurrency = false;
            string concurrencyColumn = String.Empty;

            List<string> modifiedColumns = packet.ModifiedColumns;

            foreach (esColumnMetadata col in request.Columns)
            {
                if (col.IsEntitySpacesConcurrency)
                {
                    hasConcurrency = true;
                    concurrencyColumn = col.Name;

                    sql += "DECLARE pConncurrency " + request.ProviderMetadata.GetTypeMap(col.PropertyName).NativeType + "; ";
                    break;
                }
            }

            OracleParameter p = null;
            sql += " BEGIN ";

            esColumnMetadataCollection cols = request.Columns;

            // Server-side special columns are refreshed by the DB (trigger or
            // DEFAULT). Do NOT concatenate the ServerSideText value — it is a
            // bareword that Oracle rejects with PLS-00201. The parameter is
            // registered as Output so a future RETURNING-based readback could
            // consume it; today there is no explicit SET for it.
            if (cols.DateModified != null && cols.DateModified.IsServerSide)
            {
                p = CloneParameter(types[cols.DateModified.ColumnName]);
                p.Direction = ParameterDirection.Output;
                cmd.Parameters.Add(p);
            }

            if (cols.ModifiedBy != null && cols.ModifiedBy.IsServerSide)
            {
                p = CloneParameter(types[cols.ModifiedBy.ColumnName]);
                p.Size = (int)cols.FindByColumnName(cols.ModifiedBy.ColumnName).CharacterMaxLength;
                p.Direction = ParameterDirection.Output;
                cmd.Parameters.Add(p);
            }


            if (hasConcurrency)
            {
                sql += "pConncurrency := " + Delimiters.Param + concurrencyColumn + "; ";
            }

            sql += "UPDATE " + CreateFullName(request) + " SET ";

            string computed = String.Empty;
            string comma = String.Empty;
            string and = String.Empty;
            string where = string.Empty;

            foreach (esColumnMetadata col in request.Columns)
            {
                if (col.IsInPrimaryKey) continue;
                if (col.IsAutoIncrement) continue;
                if (col.IsEntitySpacesConcurrency) continue;
                if (!IsColumnModified(packet, col)) continue;

                p = cmd.Parameters.Add(CloneParameter(types[col.Name]));

                object value = GetColumnValue(packet, col);
                p.Value = value != null ? value : DBNull.Value;

                sql += comma;
                sql += Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose + " = " + p.ParameterName;
                comma = ", ";
            }

            foreach (esColumnMetadata col in request.Columns)
            {
                if (col.IsInPrimaryKey)
                {
                    p = CloneParameter(types[col.Name]);
                    p.Value = GetOriginalColumnValue(packet, col);
                    cmd.Parameters.Add(p);

                    where += and;
                    where += Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose + " = " + p.ParameterName;
                    and = " AND ";
                }
                else if (col.IsComputed && !col.IsAutoIncrement)
                {
                    if (request.SelectedColumns != null && request.SelectedColumns.ContainsKey(col.Name))
                    {
                        p = CloneParameter(types[col.Name]);
                        p.Direction = ParameterDirection.Output;
                        if (col.CharacterMaxLength > 0)
                        {
                            p.Size = (int)col.CharacterMaxLength;
                        }
                        cmd.Parameters.Add(p);

                        if (computed.Length > 0) computed += ", ";
                        computed += " " + p.ParameterName + " = " + Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose;
                    }
                }
                if (col.IsEntitySpacesConcurrency)
                {
                    sql += ", ";
                    sql += Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose + " = " +
                      Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose + " + 1";

                    p = CloneParameter(types[col.Name]);
                    p.Direction = ParameterDirection.InputOutput;
                    p.Value = GetOriginalColumnValue(packet, col);
                    cmd.Parameters.Add(p);
                    break;
                }
            }

            sql += " WHERE (" + where + ") ";
            if (hasConcurrency)
            {
                sql += " AND \"" + concurrencyColumn + "\" = pConncurrency; ";

                sql += "IF SQL%ROWCOUNT = 1 THEN ";
                sql += Delimiters.Param + concurrencyColumn + " := pConncurrency + 1; ELSE ";
                sql += "Raise_application_error(-20101, 'NO RECORDS WERE UPDATED'); END IF;";
            }
            else
            {
                sql += ";";
            }

            if (computed.Length > 0)
            {
                sql += " SELECT " + computed + " FROM " + CreateFullName(request) + " WHERE (" + where + ")";
            }

            sql += " END;";

            cmd.CommandText = sql;
            cmd.CommandType = CommandType.Text;
            return cmd;
        }

        static public OracleCommand BuildDynamicDeleteCommand(esDataRequest request, esEntitySavePacket packet)
        {
            Dictionary<string, OracleParameter> types = Cache.GetParameters(request);

            OracleCommand cmd = new OracleCommand();
            cmd.BindByName = true;
            if (request.CommandTimeout != null) cmd.CommandTimeout = request.CommandTimeout.Value;

            string sql = String.Empty;
            bool hasConcurrency = false;

            sql += "BEGIN ";

            sql += "DELETE FROM " + CreateFullName(request) + " ";

            string where = String.Empty;
            string comma = String.Empty;

            comma = String.Empty;
            foreach (esColumnMetadata col in request.Columns)
            {
                if (col.IsInPrimaryKey || col.IsEntitySpacesConcurrency)
                {
                    OracleParameter p = CloneParameter(types[col.Name]);
                    p.Value = GetOriginalColumnValue(packet, col);
                    cmd.Parameters.Add(p);

                    where += comma;
                    where += Delimiters.ColumnOpen + col.Name + Delimiters.ColumnClose + " = " + p.ParameterName;
                    comma = " AND ";

                    if (col.IsEntitySpacesConcurrency) hasConcurrency = true;
                }
            }

            sql += " WHERE (" + where + "); ";


            if (hasConcurrency)
            {
                sql += "IF SQL%ROWCOUNT = 0 THEN ";
                sql += "Raise_application_error(-20101, 'NO RECORDS WERE DELETED'); END IF;";
            }

            sql += " END;";

            cmd.CommandText = sql;
            cmd.CommandType = CommandType.Text;
            return cmd;
        }

        static public OracleCommand BuildStoredProcInsertCommand(esDataRequest request, esEntitySavePacket packet)
        {
            Dictionary<string, OracleParameter> types = Cache.GetParameters(request);

            OracleCommand cmd = new OracleCommand();
            cmd.BindByName = true;
            if (request.CommandTimeout != null) cmd.CommandTimeout = request.CommandTimeout.Value;

            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = CreateFullSPName(request, request.ProviderMetadata.spInsert);

            PopulateStoredProcParameters(cmd, request, packet);

            esColumnMetadataCollection cols = request.Columns;
            OracleParameter p = null;

            // Iterate the parameter collection directly and match each parameter
            // back to its column metadata via SourceColumn. Cache.GetParameters sets
            // SourceColumn deterministically, so this lookup always resolves. The
            // previous approach used cmd.Parameters["p" + col.PropertyName], which
            // silently returned null for some parameters — notably the concurrency
            // column "Version" — leaving them as Input and causing the SP to receive
            // NULL where it expected the current version.
            foreach (OracleParameter existing in cmd.Parameters)
            {
                esColumnMetadata col = request.Columns.FindByColumnName(existing.SourceColumn);

                if (col == null) continue;

                bool flipToOutput =
                    col.IsComputed ||
                    col.IsAutoIncrement ||
                    col.IsEntitySpacesConcurrency ||
                    IsSpecialColumn(request.Columns, col);

                if (flipToOutput)
                {
                    existing.Direction = ParameterDirection.Output;
                }
            }

            // Special-column handling is intentionally omitted from the SP path.
            //
            // The Oracle 12c+ template emits the SP parameters for DateAdded,
            // DateModified, AddedBy and ModifiedBy as IN (never OUT), because the
            // physical columns are filled by the DB DEFAULT (SYSTIMESTAMP) or a
            // server-side trigger. There is nothing for the provider to read back.
            //
            // The previous code attempted to look up these parameters by
            // `types[colName].ParameterName`, which returns the cached name
            // (":DateAdded") rather than the name registered by
            // PopulateStoredProcParameters ("pDateAdded"). The lookup returned null
            // and the subsequent `p.ParameterName` access threw NullReferenceException
            // before the SP was even invoked.
            //
            // PopulateStoredProcParameters already adds the parameters with the
            // correct key and direction; nothing else is needed here.

            return cmd;
        }

        static public OracleCommand BuildStoredProcUpdateCommand(esDataRequest request, esEntitySavePacket packet)
        {
            Dictionary<string, OracleParameter> types = Cache.GetParameters(request);

            OracleCommand cmd = new OracleCommand();
            cmd.BindByName = true;
            if (request.CommandTimeout != null) cmd.CommandTimeout = request.CommandTimeout.Value;

            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = CreateFullSPName(request, request.ProviderMetadata.spUpdate);

            PopulateStoredProcParameters(cmd, request, packet);

            esColumnMetadataCollection cols = request.Columns;
            OracleParameter p = null;

            // Pass 1 — remove special columns. The UPDATE SP no longer declares
            // parameters for DateAdded, DateModified, AddedBy or ModifiedBy.
            // Iterate backwards so removing an item does not disturb the loop.
            for (int i = cmd.Parameters.Count - 1; i >= 0; i--)
            {
                OracleParameter existing = (OracleParameter)cmd.Parameters[i];
                esColumnMetadata col = request.Columns.FindByColumnName(existing.SourceColumn);
                if (col != null && IsSpecialColumn(request.Columns, col))
                {
                    cmd.Parameters.RemoveAt(i);
                }
            }

            // Pass 2 — mark computed and concurrency columns as InputOutput. The
            // SP declares them as "IN OUT" so the framework can read the new
            // version back after the UPDATE. Same SourceColumn-based lookup as
            // the Insert builder to avoid the string-indexer miss on "pVersion".
            foreach (OracleParameter existing in cmd.Parameters)
            {
                esColumnMetadata col = request.Columns.FindByColumnName(existing.SourceColumn);
                if (col == null) continue;

                if (col.IsComputed || col.IsEntitySpacesConcurrency)
                {
                    existing.Direction = ParameterDirection.InputOutput;
                }
            }

            return cmd;
        }

        static public OracleCommand BuildStoredProcDeleteCommand(esDataRequest request, esEntitySavePacket packet)
        {
            OracleCommand cmd = new OracleCommand();
            cmd.BindByName = true;
            if (request.CommandTimeout != null) cmd.CommandTimeout = request.CommandTimeout.Value;

            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = CreateFullSPName(request, request.ProviderMetadata.spDelete);

            Dictionary<string, OracleParameter> types = Cache.GetParameters(request);

            OracleParameter p;

            foreach (esColumnMetadata col in request.Columns)
            {
                if (col.IsInPrimaryKey || col.IsEntitySpacesConcurrency)
                {
                    p = types[col.Name];
                    p = CloneParameter(p);
                    p.ParameterName = p.ParameterName.Replace(":", "p");
                    p.Value = GetOriginalColumnValue(packet, col);
                    cmd.Parameters.Add(p);
                }
            }

            return cmd;
        }

        static public void PopulateStoredProcParameters(OracleCommand cmd, esDataRequest request, esEntitySavePacket packet)
        {
            Dictionary<string, OracleParameter> types = Cache.GetParameters(request);

            OracleParameter p;

            foreach (esColumnMetadata col in request.Columns)
            {
                p = types[col.Name];
                p = CloneParameter(p);

                p.ParameterName = p.ParameterName.Replace(":", "p");

                object v = GetColumnValue(packet, col);
                p.Value = v != null ? v : DBNull.Value;

                // Direction is decided by the caller. The previous heuristic
                // (TimeStamp → InputOutput) assumed an Oracle 11g trigger-based
                // flow where special columns were written back through the SP.
                // Oracle 12c+ fills them via DEFAULT SYSTIMESTAMP and the template
                // declares them IN, so binding them as InputOutput produces
                // PLS-00306 "wrong number or types of arguments".
                //
                // Callers override the direction explicitly:
                //   - BuildStoredProcInsertCommand / BuildStoredProcUpdateCommand
                //     flip IsComputed / IsAutoIncrement / IsEntitySpacesConcurrency
                //     columns to Output (or InputOutput for concurrency).
                //   - Everything else stays Input.

                cmd.Parameters.Add(p);
            }
        }

        static private OracleParameter CloneParameter(OracleParameter p)
        {
            ICloneable param = p as ICloneable;
            return param.Clone() as OracleParameter;
        }

        //static public string CreateFullName(esDataRequest request, esDynamicQuerySerializable query)
        static public string CreateFullName(esDataRequest request, esDynamicQuery query)
        {
            //IDynamicQuerySerializableInternal iQuery = query as IDynamicQuerySerializableInternal;
            IDynamicQueryInternal iQuery = query as IDynamicQueryInternal;

            esProviderSpecificMetadata providerMetadata = iQuery.ProviderMetadata as esProviderSpecificMetadata;

            string name = String.Empty;

            string schema = iQuery.Schema ?? request.Schema ?? providerMetadata.Schema;

            if (schema != null)
            {
                name += Delimiters.TableOpen + schema + Delimiters.TableClose + ".";
            }

            name += Delimiters.TableOpen;
            if (query.querySource != null)
                name += query.querySource;
            else
                name += providerMetadata.Destination;
            name += Delimiters.TableClose;

            return name;
        }

        static public string CreateFullName(esDataRequest request)
        {
            string name = String.Empty;

            string schema = request.Schema ?? request.ProviderMetadata.Schema;

            if (schema != null)
            {
                name += Delimiters.TableOpen + schema + Delimiters.TableClose + ".";
            }

            name += Delimiters.TableOpen;
            if (request.DynamicQuery != null && request.DynamicQuery.querySource != null)
                name += request.DynamicQuery.querySource;
            else
                name += request.QueryText != null ? request.QueryText : request.ProviderMetadata.Destination;


            name += Delimiters.TableClose;

            return name;
        }

        static public string CreateFullSPName(esDataRequest request, string spName)
        {
            string name = String.Empty;

            if (request.Schema != null || request.ProviderMetadata.Schema != null)
            {
                name += Delimiters.TableOpen;
                name += request.Schema != null ? request.Schema : request.ProviderMetadata.Schema;
                name += Delimiters.TableClose + ".";
            }

            name += Delimiters.StoredProcNameOpen;
            name += spName;
            name += Delimiters.StoredProcNameClose;

            return name;
        }

        static public esConcurrencyException CheckForConcurrencyException(OracleException ex)
        {
            esConcurrencyException ce = null;

            if (ex != null)
            {
                // ORA-20101: custom application error raised by EntitySpaces stored procs
                //            ("NO RECORDS WERE UPDATED" / "NO RECORDS WERE DELETED")
                // ORA-00001: unique constraint violated (duplicate PK on insert)
                // ORA-00060: deadlock detected while waiting for resource
                // ORA-08177: can't serialize access for this transaction (serializable isolation)
                //
                // ex.Number contains the Oracle error number (sign-stripped, e.g. -20101 → 20101).
                // Note: ORA-20101 is raised as a negative number by Raise_application_error,
                //       but OracleException.Number returns the absolute value.
                switch (ex.Number)
                {
                    case 20101:  // custom stored-proc concurrency error
                    case 1:      // ORA-00001 unique constraint violated
                    case 60:     // ORA-00060 deadlock detected
                    case 8177:   // ORA-08177 can't serialize access
                        ce = new esConcurrencyException(ex.Message, ex);
                        ce.Source = ex.Source;
                        break;
                }
            }

            return ce;
        }

        static public void AddParameters(OracleCommand cmd, esDataRequest request)
        {
            if (request.QueryType == esQueryType.Text && request.QueryText != null && request.QueryText.Contains("{0}"))
            {
                int i = 0;
                string token = String.Empty;
                string sIndex = String.Empty;
                string param = String.Empty;

                foreach (esParameter esParam in request.Parameters)
                {
                    sIndex = i.ToString();
                    token = '{' + sIndex + '}';
                    param = Delimiters.Param + "p" + sIndex;
                    request.QueryText = request.QueryText.Replace(token, param);
                    i++;

                    OracleParameter p = new OracleParameter(Delimiters.Param + esParam.Name, esParam.Value);
                    cmd.Parameters.Add(p);
                }
            }
            else
            {
                OracleParameter param;

                string paramPrefix = request.QueryType == esQueryType.StoredProcedure ? String.Empty : Delimiters.Param;
                paramPrefix = request.ProviderMetadata.spLoadByPrimaryKey == request.QueryText ? "p" : paramPrefix;

                foreach (esParameter esParam in request.Parameters)
                {
                    param = new OracleParameter(paramPrefix + esParam.Name, esParam.Value);
                    cmd.Parameters.Add(param);

                    // The default is ParameterDirection.Input
                    switch (esParam.Direction)
                    {
                        case esParameterDirection.InputOutput:
                            param.Direction = ParameterDirection.InputOutput;
                            break;

                        case esParameterDirection.Output:
                            param.Direction = ParameterDirection.Output;
                            param.DbType = esParam.DbType;
                            param.Size = esParam.Size;
                            // Precision and Scale are obsolete for Oracle
                            // and are ignored.
                            //param.Scale = esParam.Scale;
                            //param.Precision = esParam.Precision;
                            break;

                        case esParameterDirection.ReturnValue:
                            param.Direction = ParameterDirection.ReturnValue;
                            break;
                    }
                }
            }
        }

        static public void GatherReturnParameters(OracleCommand cmd, esDataRequest request, esDataResponse response)
        {
            if (cmd.Parameters.Count > 0)
            {
                if (request.Parameters != null && request.Parameters.Count > 0)
                {
                    string paramPrefix = request.QueryType == esQueryType.StoredProcedure ? String.Empty : Delimiters.Param;
                    paramPrefix = request.ProviderMetadata.spLoadByPrimaryKey == request.QueryText ? "p" : paramPrefix;

                    response.Parameters = new esParameters();

                    foreach (esParameter esParam in request.Parameters)
                    {
                        if (esParam.Direction != esParameterDirection.Input)
                        {
                            response.Parameters.Add(esParam);
                            OracleParameter p = cmd.Parameters[paramPrefix + esParam.Name];
                            esParam.Value = p.Value;
                        }
                    }
                }
            }
        }

        // ===================================================================
        // Tolerant column/property name resolution.
        //
        // Oracle folds unquoted identifiers to UPPERCASE, so the physical
        // column name ("INVOICEID") diverges from the EntitySpaces property
        // name ("Invoiceid") emitted by Studio. The framework writes under
        // BOTH keys depending on the code path:
        //   - Typed property setter  -> ColumnNames.X    ("INVOICEID")
        //   - ApplyPostSaveKeys      -> PropertyNames.X  ("Invoiceid")
        // Both must be recognized.
        // ===================================================================

        static private bool IsColumnModified(esEntitySavePacket packet, esColumnMetadata col)
        {
            if (packet.ModifiedColumns == null) return false;

            foreach (string m in packet.ModifiedColumns)
            {
                if (string.Equals(m, col.Name, StringComparison.OrdinalIgnoreCase)) return true;
                if (!string.IsNullOrEmpty(col.PropertyName) &&
                    string.Equals(m, col.PropertyName, StringComparison.OrdinalIgnoreCase)) return true;
            }
            return false;
        }

        static private object GetColumnValue(esEntitySavePacket packet, esColumnMetadata col)
        {
            if (packet.CurrentValues == null) return null;

            object byColumn = null;
            if (packet.CurrentValues.ContainsKey(col.Name))
                byColumn = packet.CurrentValues[col.Name];

            if (byColumn != null && byColumn != DBNull.Value) return byColumn;

            if (!string.IsNullOrEmpty(col.PropertyName) &&
                packet.CurrentValues.ContainsKey(col.PropertyName))
            {
                object byProperty = packet.CurrentValues[col.PropertyName];
                if (byProperty != null && byProperty != DBNull.Value) return byProperty;
            }

            return byColumn;
        }

        static private object GetOriginalColumnValue(esEntitySavePacket packet, esColumnMetadata col)
        {
            if (packet.OriginalValues == null) return null;

            object byColumn = null;
            if (packet.OriginalValues.ContainsKey(col.Name))
                byColumn = packet.OriginalValues[col.Name];

            if (byColumn != null && byColumn != DBNull.Value) return byColumn;

            if (!string.IsNullOrEmpty(col.PropertyName) &&
                packet.OriginalValues.ContainsKey(col.PropertyName))
            {
                object byProperty = packet.OriginalValues[col.PropertyName];
                if (byProperty != null && byProperty != DBNull.Value) return byProperty;
            }

            return byColumn;
        }

        // Fix F: matches the four EntitySpaces special columns by name.
        // The metadata's IsSpecialColumn helper exists but relies on
        // runtime state (cols.DateAdded, cols.DateModified, etc.) being
        // populated, which is not guaranteed in every save path. A
        // name-based check is deterministic.
        static private bool IsSpecialColumn(esColumnMetadataCollection columns, esColumnMetadata col)
        {
            if (col == null || string.IsNullOrEmpty(col.Name)) return false;

            // Prefer the metadata-driven check when available.
            try { if (columns != null && columns.IsSpecialColumn(col)) return true; }
            catch { /* fall through to name match */ }

            string n = col.Name.ToLowerInvariant();
            return n == "dateadded"
                || n == "datemodified"
                || n == "addedby"
                || n == "modifiedby";
        }


    } // end class
}
