<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Version>2026.09</Version>
    <AssemblyVersion>2026.9.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Proveedores de Bases de Datos -->
    <PackageVersion Include="Microsoft.Data.SqlClient" Version="7.1.0" />
    <PackageVersion Include="MySqlConnector" Version="2.6.2" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="Oracle.ManagedDataAccess.Core" Version="23.26.301" />
    <PackageVersion Include="FirebirdSql.Data.FirebirdClient" Version="10.3.4" />
    <PackageVersion Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageVersion Include="System.Data.OleDb" Version="10.0.12" />

    <!-- Compilación Dinámica con Roslyn -->
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.12" />

    <!-- UI y Docking -->
    <PackageVersion Include="WeifenLuo.WinFormsUI.Docking" Version="2.1.0" />

    <!-- Infraestructura y Extensiones de .NET -->
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="10.0.12" />
    <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="10.0.12" />
    <PackageVersion Include="System.Management" Version="10.0.12" />

    <!-- Interop y Extensibilidad de Visual Studio -->
    <PackageVersion Include="EnvDTE" Version="16.7.30328.74" />
    <PackageVersion Include="EnvDTE80" Version="16.7.30328.74" />
    <PackageVersion Include="EnvDTE90" Version="16.7.30328.74" />
    <PackageVersion Include="EnvDTE100" Version="16.7.30328.74" />
    <PackageVersion Include="Microsoft.VisualStudio.CommandBars" Version="16.7.30328.74" />
    <PackageVersion Include="Microsoft.VisualStudio.SDK.EmbedInteropTypes" Version="15.0.36" />
    <PackageVersion Include="stdole" Version="17.14.40260" />
  </ItemGroup>
</Project>