<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
		<OutputType>Library</OutputType>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

		<!-- Firma del ensamblado -->
		<!--<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>..\StrongNameKey\EntitySpaces.snk</AssemblyOriginatorKeyFile>-->

		<!-- Documentación XML opcional para Debug -->
		<DocumentationFile Condition="'$(Configuration)'=='Debug'">bin\Debug\net8.0\EntitySpaces.MetadataEngine.xml</DocumentationFile>
		<PlatformTarget>x86</PlatformTarget>
	</PropertyGroup>

	<!-- Constantes condicionales para Release -->
	<PropertyGroup Condition="'$(Configuration)|$(Release)'=='true' Or '$(Configuration)'=='Release'">
		<DefineConstants>TRACE;ENTERPRISE</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="CollectionEnumerator.cs" />
	  <Compile Remove="IClassFactory.cs" />
	  <Compile Remove="Properties\AssemblyInfo.cs" />
	  <Compile Remove="Utility.cs" />
	</ItemGroup>

	<!-- Referencias a Paquetes NuGet (versiones gestionadas por Directory.Packages.props) -->
	<ItemGroup>
		<!-- Proveedores de Bases de Datos -->
		<PackageReference Include="FirebirdSql.Data.FirebirdClient" />
		<PackageReference Include="Microsoft.Data.SqlClient" />
		<PackageReference Include="MySqlConnector" />
		<PackageReference Include="Npgsql" />
		<PackageReference Include="Oracle.ManagedDataAccess.Core" />
		<PackageReference Include="System.Data.OleDb" />
		<PackageReference Include="System.Data.SQLite.Core" />
	</ItemGroup>

	<!-- Archivos compartidos externos -->
	<ItemGroup>
		<Compile Include="..\..\SharedFiles\Crypto.cs" Link="Crypto.cs" />
		<Compile Include="..\..\SharedFiles\SharedVersion.cs" Link="SharedVersion.cs" />
	</ItemGroup>

	<!-- Clave de seguridad como recurso o archivo vinculado -->
	<ItemGroup><!--Signed File notbinary compatibilty-->
		<!--<None Include="..\..\StrongNameKey\EntitySpaces.snk" Link="EntitySpaces.snk" />-->
	
	  <Compile Remove="Access\**" />
	  <Compile Remove="VistaDB3x\**" />
	  <Compile Remove="VistaDB\**" />
	  <EmbeddedResource Remove="Access\**" />
	  <EmbeddedResource Remove="VistaDB3x\**" />
	  <EmbeddedResource Remove="VistaDB\**" />
	  <None Remove="Access\**" />
	  <None Remove="VistaDB3x\**" />
	  <None Remove="VistaDB\**" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="Interop.ADOX.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Interop.MSDASC.dll">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>